login_redirection:
  anonymous: null
  authenticated: /admin/content?check_logged_in=1
  content_editor: /admin/content?check_logged_in=1
  administrator: /admin/content?check_logged_in=1
exclude_urls: ''
