<?php

/**
 * Implements hook_page_attachments().
 */
function google_meta_header_page_attachments(array &$attachments) {
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'origin-trial',
        'content' => 'Aomym0nj3uR10aC0Vdv25S3Jfg3LT4OCWdImpTaXbYFLxX8f+vOJ8E4awy/AKMX55EYoqXfMpsmiGkoq3pb0HAsAAAB2eyJvcmlnaW4iOiJodHRwczovL2RydXBhbGZvcmdlLmFwcDo0NDMiLCJmZWF0dXJlIjoiQUlQcm9tcHRBUElNdWx0aW1vZGFsSW5wdXQiLCJleHBpcnkiOjE3ODE1NjgwMDAsImlzU3ViZG9tYWluIjp0cnVlfQ==',
      ],
    ],
    'google_meta_header_origin_trial_1',
  ];

  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'origin-trial',
        'content' => 'AhFOM1N7SRKckLSvU/QyzPLqVwY+nw+3V9SXybpeB/ytCwIETXNQcx8N8CDX0GRX5VlVPNJYirIQpZDOxuK10wIAAABseyJvcmlnaW4iOiJodHRwczovL2RydXBhbGZvcmdlLmFwcDo0NDMiLCJmZWF0dXJlIjoiQUlQcm9vZnJlYWRlckFQSSIsImV4cGlyeSI6MTc3OTE0ODgwMCwiaXNTdWJkb21haW4iOnRydWV9',
      ],
    ],
    'google_meta_header_origin_trial_2',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'origin-trial',
        'content' => 'AgxTMn1BZPWyfzpXOr7H49e4TbKe4hruKJ0TW9MMVBzwth9/ZppMwQY9sAQnW4GIXRpgb6BAPRQZNyjBAETJ4goAAABpeyJvcmlnaW4iOiJodHRwczovL2RydXBhbGZvcmdlLmFwcDo0NDMiLCJmZWF0dXJlIjoiQUlSZXdyaXRlckFQSSIsImV4cGlyeSI6MTc3NjcyOTYwMCwiaXNTdWJkb21haW4iOnRydWV9',
      ],
    ],
    'google_meta_header_origin_trial_3',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'origin-trial',
        'content' => 'An9AiNnlyuj48AurVMnC/AvZ9EJbw+A35S7YxfLSLDMUk2knqPKZuNSA4azG1+I4BNcEwI7T/s8rO6OKQuJlvQAAAABneyJvcmlnaW4iOiJodHRwczovL2RydXBhbGZvcmdlLmFwcDo0NDMiLCJmZWF0dXJlIjoiQUlXcml0ZXJBUEkiLCJleHBpcnkiOjE3NzY3Mjk2MDAsImlzU3ViZG9tYWluIjp0cnVlfQ==',
      ],
    ],
    'google_meta_header_origin_trial_4',
  ];
}
